In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd 
import numpy as np

In [7]:
### Load the ANN train model, scalar pickle file, OneHotencoding file
model = load_model('model.h5')

## load encoder and scaler
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('ohe_geo.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)


with open('scaler.pkl', 'rb') as file:
    scaler= pickle.load(file)

In [6]:
## example input data
# Example input data - Test 2
input_data = {
    'CreditScore': 720,
    'Geography': 'Germany',
    'Gender': 'Female',
    'Age': 32,
    'Tenure': 7,
    'Balance': 85000,
    'NumOfProducts': 1,
    'HasCrCard': 0,
    'IsActiveMember': 0,
    'EstimatedSalary': 75000
}

In [8]:
## One hot encoding "geography"
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\Ayan\Desktop\ANN_Project\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               0.0                1.0              0.0

In [10]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,720,Germany,Female,32,7,85000,1,0,0,75000

In [11]:
input_data = pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,720,Germany,Female,32,7,85000,1,0,0,75000,0.0,1.0,0.0

In [12]:
## Encode categoroical variable
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,720,Germany,0,32,7,85000,1,0,0,75000

In [14]:
## concat.. with ohe data to the data
input_df=pd.concat([input_df.drop("Geography", axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,720,0,32,7,85000,1,0,0,75000,0.0,1.0,0.0

In [15]:
## scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[ 0.70934256, -1.09499335, -0.6557859 ,  0.69270405,  0.14246355,
        -0.91668767, -1.54035103, -1.02583358, -0.44216545, -0.99850112,
         1.72572313, -0.57638802]])

In [ ]:
## prediction 
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 14ms/step

array([[0.3177429]], dtype=float32)

In [19]:
## prediction probab
prediction_probab = prediction[0][0]
prediction_probab

0.3177429

In [20]:
if prediction_probab >0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.